name: Build thesis

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: TeX-Live/setup-texlive-action@v4
      with:
        packages: >-
          texliveonfly
          scheme-basic
          hyperref
          latexmk
          biblatex
          xelatex
          xetex
          threeparttable
          multirow
          longtable
          algorithms
          ctex
          iftex
          kvdefinekeys
          kvsetkeys
          kvoptions
          etoolbox
          filehook
          xparse
          geometry
          fancyhdr
          amsmath
          graphicx
          caption
          pdfpages
          footmisc
          xecjk
          array
          booktabs
          fontenc
          bm
          float
          biblatex-gb7714-2015
          biber
          biber-windows
          collection-latexrecommended
          collection-mathscience
          tocloft
          eso-pic
          microtype
          ragged2e
          chngcntr
          pifont
    - run: DISM.exe /Online /Add-Capability /CapabilityName:Language.Fonts.Hans~~~und-HANS~0.0.1.0
    - run: latexmk main.tex
    - run: latexmk -c
    
    - uses: actions/upload-artifact@v4
      with:
        name: main pdf
        path: main.pdf
